# Generated by Django 6.0.2 on 2026-03-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_alter_device_id"),
        ("users", "0004_adgroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adgroup",
            name="members",
        ),
        migrations.AddField(
            model_name="adgroup",
            name="devices",
            field=models.ManyToManyField(related_name="devices", to="devices.device"),
        ),
    ]
