# Generated by Django 6.0.2 on 2026-03-01 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_alter_device_id"),
        ("users", "0005_remove_adgroup_members_adgroup_devices"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="devices.device",
            ),
        ),
    ]
