# Generated by Django 6.0.2 on 2026-02-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('secret_key', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('assigned_ads', models.ManyToManyField(blank=True, to='ads.ad')),
            ],
        ),
    ]
