# Generated by Django 6.0.2 on 2026-02-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
