# Generated by Django 6.0.2 on 2026-02-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlog",
            old_name="played_at",
            new_name="started_at",
        ),
        migrations.AddField(
            model_name="playlog",
            name="finished_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="playlog",
            name="status",
            field=models.CharField(default="Playing"),
        ),
        migrations.AddField(
            model_name="playlog",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="playlog",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
