# Generated by Django 6.0.2 on 2026-02-20 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_rename_played_at_playlog_started_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2026, 2, 20, 13, 6, 0, 708943),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="playlog",
            name="started_at",
            field=models.DateTimeField(null=True),
        ),
    ]
