# Generated by Django 6.0.2 on 2026-02-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_ad_created_by_alter_ad_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
