# Generated by Django 6.0.2 on 2026-02-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_alter_ad_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="advideo",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advideo",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="ads/thumbs/"),
        ),
    ]
